-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 17:56:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema porfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema porfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `porfolio` DEFAULT CHARACTER SET utf8 ;
USE `porfolio` ;

-- -----------------------------------------------------
-- Table `porfolio`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paginas` INT(10) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha-nacimiento` DATE NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `sobre-mi` VARCHAR(100) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `img-perfil` VARCHAR(255) NULL,
  `img-fondo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`educacion` (
  `id` INT NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha-inicio` VARCHAR(25) NULL,
  `fecha-fin` VARCHAR(25) NULL,
  `logo` VARCHAR(250) NULL,
  `url` VARCHAR(250) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_educacion_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `porfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porfolio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`usuarios` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_usuarios_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `porfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porfolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`proyectos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha-creacion` VARCHAR(25) NULL,
  `foto` VARCHAR(250) NULL,
  `url` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_proyectos_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `porfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porfolio`.`tecnologias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `porfolio`.`tecnologias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `porcentaje` INT NULL,
  `logo` VARCHAR(250) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_tecnologias_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_tecnologias_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `porfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
